### ISSUE TITLE
Mis-labelled column in systems metadata: `panel_capacity_W_each`

### ISSUE THREAD

**Issue by JamieTaylor-TUOS** [openclimatefix/pvoutput#48]
When downloading system metadata using either `search()` or `get_metadata()`, you have labelled the `System Size` field from PVOutput as `system_AC_capacity_W`, but I think this may actually be the _**DC**_ capacity of the system, since it seems to correspond to `Panels` multiplied by `Panel Power` (or `num_panels` multiplied by `panel_capacity_W_each` using OCF notation). Also, the `Inverter Power` (`inverter_capacity_W`) is recorded separately, and is typically considered the "AC capacity" of the system. The API docs don't make this clear though so I could be wrong.

PR to follow...

**Comment by JackKelly** [comment]
Good catch!  Thanks Jamie!
