### ISSUE TITLE
Add github actions pytest

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvoutput#52]
## Detailed Description
Add github actinos workflow to run pytests

## Context
Good to have auto CI

## Possible Implementation
See https://github.com/openclimatefix/nowcasting_dataset/blob/main/.github/workflows/workflows.yaml

**Comment by Antsthebul** [comment]
Id like to give this a shot

**Comment by peterdudfield** [comment]
Thanks @Antsthebul, any help would really be appreciated. 

Let me know if you need anything to support on you on this
