### ISSUE TITLE
Make into pypi library

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvoutput#70]
## Detailed Description
Would be great if this could be install with `pip install pvoutput`

## Context
Useful for other people to use

## Possible Implementation
maybe like this?
https://github.com/openclimatefix/nowcasting_dataset/blob/main/.github/workflows/release.yaml

**Comment by JackKelly** [comment]
So, `pvoutput` is a python library with a `setup.py` which can be installed using `pip install -e git+https://github.com/openclimatefix/pvoutput#egg=pvoutput`.

But perhaps it would be nice to have this installable from P

**Comment by JackKelly** [comment]
maybe we could close this issue and create a new one to add `pvoutput` to `pypi`?

**Comment by peterdudfield** [comment]
Thanks @JackKelly, Ive updated the title and description, to change it to install this from pypi.

**Comment by peterdudfield** [comment]
this is now done - https://pypi.org/project/pvoutput-ocf/
