### ISSUE TITLE
pre-commit error - No such file or directory: 'nowcasting_dataset'

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvoutput#74]
**Describe the bug**
pre-commit issue. 
Found by @Antsthebul
more detailed in this [PR](https://github.com/openclimatefix/pvoutput/pull/68)

**To Reproduce**
1. clone repo
2. try to commit something

**Additional context**
[Add any other context about the problem here.](https://github.com/openclimatefix/pvoutput/pull/68)

**Comment by Antsthebul** [comment]
I wasnt sure if this file was supposed to exist or not. So didnt want to remove it from the pre-commit config file. Im guessing it is supposed to be there?

**Comment by peterdudfield** [comment]
Ah i see, it should get changed to the library folder i.e pvoutput

**Comment by peterdudfield** [comment]
Thanks @Antsthebul for pointing this out. Should be fixed in https://github.com/openclimatefix/pvoutput/commit/851750c23d94c526fedd745484d165b0aab3bc23
